### ISSUE TITLE
adding an example of how to get the value of a cross-contract call in a contract

### ISSUE THREAD

**Issue by Scofield-04-21-076** [near-examples/cross-contract-hello-rust#4]
Hi, while studying the NEAR Protocol, I encountered the following question: how to get the value of an cross-contract call not in a command line request or a JavaScript request, but in one of the methods of the contract to further interact with the received value. That is, something like this:

```rs
    pub fn method(&self, greeting_2: String) -> String {
          ....
          let greeting = self.query_greeting().value;
          greeting + greeting_2
    }
```

I propose to add an example of how to solve this issue, because it is quite useful to handle the value of the cross-contract call in the contract itself, and it will also help beginners in learning the Near Protocol.

**Comment by gagdiez** [comment]
Hi! you can't, since all cross-contract calls in NEAR are asynchronous, please [check our documentation here](https://docs.near.org/develop/contracts/crosscontract)
